### ISSUE TITLE
Failed to generate schema error

### ISSUE THREAD

**Issue by nasdf** [graphprotocol/graph-client#138]
I can't seem to get a client generated from our graph endpoint.

`package.json`

```
{
  "scripts": {
    "build": "graphclient build"
  },
  "devDependencies": {
    "@graphprotocol/client-cli": "^2.0.1"
  }
}
```

`.graphclientrc.yaml`

```
sources:
  - name: valist
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/valist-io/valist
```

Error output below.

```
💡 GraphClient Cleaning existing artifacts
💡 GraphClient Reading the configuration
💡 GraphClient Generating the unified schema
💥 GraphClient - valist Failed to generate the schema Error: Failed to fetch introspection from https://api.thegraph.com/subgraphs/name/valist-io/valist: TypeError: Request with GET/HEAD method cannot have body.
    at new Request (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/undici/lib/fetch/request.js:437:13)
    at Agent.fetch (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/undici/lib/fetch/index.js:114:21)
    at fetch (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/undici/index.js:90:22)
    at fetch (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/cross-undici-fetch/dist/create-node-ponyfill.js:130:16)
    at /Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/fetchache/index.js:21:36
    at async Object.getWithSet (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/@graphql-mesh/store/index.js:155:38)
    at GraphQLHandler.getMeshSource (/Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/@graphql-mesh/graphql/index.js:295:23)
    at async /Users/keenan/Projects/valist/valist/valist-js/packages/valist-graph-client/node_modules/@graphql-mesh/runtime/index.js:219:28
💥 GraphClient Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 e...
```

**Comment by tmigone** [comment]
I was hitting the same error, upgrading `@graphprotocol/client-cli` to `v2.0.2` fixed it.
