### ISSUE TITLE
example for graphclient --js does not work

### ISSUE THREAD

**Issue by shaddamciv** [graphprotocol/graph-client#251]
Steps 
1. Clone repo
2. Run yarn
3. Goto examples folder and run

 graphclient build --fileType js gives the following output. 

Note, that I used the sushi example instead of the given one. 

Running graphclient build --fileType json works

Environment  - wsl ubuntu 20.04, node 16.10.0

```

💥 GraphClient - Sushi Failed to generate the schema Error: Failed to fetch introspection from https://api.thegraph.com/subgraphs/name/sushiswap/exchange: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/my-projects/graph-client/examples/javascript-esm/.graphclient/sources/Sushi/introspectionSchema.js from /home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/utils/index.js not supported.
Instead change the require of introspectionSchema.js in /home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/utils/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/home/my-projects/graph-client/examples/javascript-esm/node_modules/ts-node/dist/index.js:851:20)
    at /home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/utils/index.js:37:83
    at new Promise (<anonymous>)
    at Object.defaultImportFn (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/utils/index.js:37:24)
    at Object.importFn (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/cli/index.js:997:45)
    at FsStoreStorageAdapter.write (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/store/index.js:65:28)
    at async Object.set (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/store/index.js:183:17)
    at async Object.getWithSet (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/store/index.js:165:25) {
  code: 'ERR_REQUIRE_ESM'
}
    at GraphQLHandler.getMeshSource (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/graphql/index.js:304:23)
    at async /home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/runtime/index.js:517:28
💥 GraphClient Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
    at Object.getMesh (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/runtime/index.js:550:15)
    at async Object.handler (/home/my-projects/graph-client/examples/javascript-esm/node_modules/@graphql-mesh/cli/index.js:1039:53)
```

**Comment by ardatan** [comment]
You need to configure your package.json for ESM like here by adding `type: module` etc;
https://github.com/graphprotocol/graph-client/tree/main/examples/javascript-esm

**Comment by filipv-eth** [comment]
@ardatan having the same issue, even when using the example provided in `graph-client`.

**Comment by ardatan** [comment]
Please create a reproduction on CodeSandbox or StackBlitz. Thanks!

**Comment by ardatan** [comment]
Closing the issue for now. Feel free to create a new one with a reproduction if you still have the problem.
