### ISSUE TITLE
Unable to build without specified fileType, then unable to import module

### ISSUE THREAD

**Issue by ketys-from-meiro** [graphprotocol/graph-client#416]
Hi there, I've got a problem with building `.graphclient` files by running command `graphclient build`. In this case it throws me following error:
```
Failed to generate the schema Error: Failed to fetch introspection from https://api.thegraph.com/subgraphs/name/0xrusowsky/use-arrow: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/hodlmao/Developer/arrow-frontend/.graphclient/sources/use-arrow/introspectionSchema.ts
    at new NodeError (node:internal/errors:393:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
    at GraphQLHandler.getMeshSource (/Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/graphql/cjs/index.js:336:23)
    at async /Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:133:28
    at async Promise.allSettled (index 0)
    at async getMesh (/Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:128:5)
    at async Object.handler (/Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/cli/cjs/index.js:305:53)
💥 GraphClient Error: Schemas couldn't be generated successfully. Check for the logs by running Mesh with DEBUG=1 environmental variable to get more verbose output.
    at getMesh (/Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/runtime/cjs/get-mesh.js:167:15)
    at async Object.handler (/Users/hodlmao/Developer/arrow-frontend/node_modules/@graphql-mesh/cli/cjs/index.js:305:53)
error Command failed with exit code 1.
```

I've been trying to do some stuff to figure out if something will work and was able to build it with `graphclient build --fileType js` command successfully. But the different problem occurred when I've tried to import `getBuiltGraphSDK` from the built module. I've received following error in my `vite@4.1.4` app:
```
[vite] Internal server error: Failed to resolve entry for package "/Users/hodlmao/Developer/arrow-frontend/.graphclient". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/hodlmao/Developer/arrow-frontend/src/views/Arrow/OpenPositions/OpenPositions.tsx
      at packageEntryFailure (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22005:11)
      at resolvePackageEntry (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22002:5)
      at tryResolveFile (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21610:38)
      at tryFsResolve (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21588:16)
      at Context.resolveId (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21430:28)
      at Object.resolveId (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41612:46)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.resolve (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41363:23)
      at async normalizeUrl (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39698:34)
      at async TransformContext.transform (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///Users/holdmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///Users/hodlmao/Developer/arrow-frontend/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
``` 

Can someone tell me what I'm doing wrong or if there's some bug? I was trying to resolve it past few hours :-( Thanks!

**Comment by ketys-from-meiro** [comment]
ah I cannot have `"type": "module"` in my app `package.json`, then it starts magically working

**Comment by KoanProtocol** [comment]
Mine is "type": "module"  but it I have same issue

I have been working with gitpod web, and it's been working fine. I notice this issue the moment I first imported the project to my vscode locally. I am using windows, hp
Is it an issue with OS??

I am already going crazy now, I am just stagnant

**Comment by IbrahimIjai** [comment]
Mine is "type": "module" but it I have same issue

I have been working with gitpod web, and it's been working fine. I notice this issue the moment I first imported the project to my vscode locally. I am using windows, hp
Is it an issue with OS??

I am already going crazy now, I am just stagnant
